name: Daily Token Tweet

on:
  schedule:
    # Uruchamia workflow codziennie o północy UTC (00:00 UTC)
    # Możesz dostosować godzinę, np. '0 8 * * *' dla 08:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Umożliwia ręczne uruchomienie workflow z zakładki Actions

jobs:
  tweet-top-tokens:
    runs-on: ubuntu-latest # Użyj najnowszego dostępnego środowiska Ubuntu

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Możesz wybrać wersję Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python bot.py
